-- Looking to combine all the data in the different tables into one all emcompasing temp table

WITH hotels AS(
SELECT*
FROM [Portfolio Project].[dbo].[2018]
UNION
SELECT*
FROM [Portfolio Project].[dbo].[2019]
UNION
SELECT*
FROM [Portfolio Project].[dbo].[2020])

--SELECT* FROM hotels

--Looking at the change in revenue with respect to years
--SELECT (stays_in_weekend_nights + stays_in_week_nights)*adr AS revenue FROM hotels

--SELECT arrival_date_year,SUM((stays_in_weekend_nights + stays_in_week_nights)*adr) AS total_revenue 
--FROM hotels
--GROUP BY arrival_date_year
--ORDER BY total_revenue DESC--

--looking to investigate the revenue generated by hotel type

--SELECT arrival_date_year,hotel,ROUND(SUM((stays_in_weekend_nights + stays_in_week_nights)*adr),2) AS total_revenue 
--FROM hotels
--GROUP BY arrival_date_year,hotel

--looking at the relationship between the marketsegment table and the hotels table and the meal cost table


SELECT*
FROM hotels h
LEFT JOIN [Portfolio Project].[dbo].[market_segment] s
ON h.market_segment=s.market_segment
LEFT JOIN [Portfolio Project].[dbo].[meal_cost] m
ON h.meal=m.meal;

--Looking at the total revenue generated by each market segment

SELECT s.market_segment,SUM((stays_in_weekend_nights + stays_in_week_nights)*adr) AS total_revenue
FROM hotels h
LEFT JOIN [Portfolio Project].[dbo].[market_segment] s
ON h.market_segment=s.market_segment
LEFT JOIN [Portfolio Project].[dbo].[meal_cost] m
ON h.meal=m.meal
GROUP BY s.market_segment
ORDER BY 2 DESC;

--Looking at running revenue total with respect to years

